CREATE UNIQUE INDEX IF NOT EXISTS ux_users_single_superadmin ON users(is_superadmin) WHERE is_superadmin=1;
CREATE INDEX IF NOT EXISTS ix_users_role_status ON users(role_id,status);
CREATE INDEX IF NOT EXISTS ix_role_features_feature ON role_features(feature_id);
CREATE INDEX IF NOT EXISTS ix_features_parent_sort ON features(parent_id,sort_order,id);
CREATE INDEX IF NOT EXISTS ix_collection_rules_source_enabled ON collection_rules(source_id,enabled);
CREATE UNIQUE INDEX IF NOT EXISTS ux_lookout_sources_code ON lookout_sources(code) WHERE code<>'';
CREATE INDEX IF NOT EXISTS ix_collection_runs_created ON collection_runs(created_at DESC);
CREATE INDEX IF NOT EXISTS ix_collection_results_run ON collection_results(run_id,id);
CREATE INDEX IF NOT EXISTS ix_warehouse_created ON warehouse_items(created_at DESC);
CREATE INDEX IF NOT EXISTS ix_warehouse_deep ON warehouse_items(deep_collected,created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS ux_model_single_default ON model_configs(is_default) WHERE is_default=1;
CREATE INDEX IF NOT EXISTS ix_models_type_enabled ON model_configs(model_type,enabled);
CREATE INDEX IF NOT EXISTS ix_model_usage_model_created ON model_usage(model_id,created_at DESC);
CREATE INDEX IF NOT EXISTS ix_digital_employees_type_enabled ON digital_employees(employee_type,enabled,id DESC);
CREATE INDEX IF NOT EXISTS ix_deep_tasks_item_created ON deep_collection_tasks(warehouse_item_id,id DESC);
CREATE INDEX IF NOT EXISTS ix_deep_tasks_status_created ON deep_collection_tasks(status,id DESC);
CREATE INDEX IF NOT EXISTS ix_deep_logs_task ON deep_collection_logs(task_id,id);
CREATE INDEX IF NOT EXISTS ix_deep_results_item_created ON deep_collection_results(warehouse_item_id,id DESC);
CREATE INDEX IF NOT EXISTS ix_user_conversations_user_updated ON user_conversations(user_id,updated_at DESC,id DESC);
CREATE INDEX IF NOT EXISTS ix_user_messages_conversation ON user_messages(conversation_id,id);
